export const ConfigKeys = {
  PORT: 'PORT',
  LOG_LEVEL: 'LOG_LEVEL',
  // jwt
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',

  // mongo
  MONGO_URI: 'MONGO_URI',
  MONGO_DATABASE: 'MONGO_DATABASE',

  //twitter
  TWITTER_OAUTH_CLIENT_ID: 'TWITTER_OAUTH_CLIENT_ID',
  TWITTER_OAUTH_CLIENT_SECRET: 'TWITTER_OAUTH_CLIENT_SECRET',
  TWITTER_OAUTH_TOKEN_API_URL: 'TWITTER_OAUTH_TOKEN_API_URL',
  TWITTER_OAUTH_REDIRECT_URI: 'TWITTER_OAUTH_REDIRECT_URI',
  TWITTER_TOKEN_API_URL: 'TWITTER_TOKEN_API_URL',
  TWITTER_USERINFO_API_URL: 'TWITTER_USERINFO_API_URL',
  TWITTER_BEARER_TOKEN: 'TWITTER_BEARER_TOKEN',
  TWITTER_PUBLIC_BEARER_TOKEN: 'TWITTER_PUBLIC_BEARER_TOKEN',
  TWITTER_PUBLIC_GET_TWEET_BY_ID_URL: 'TWITTER_PUBLIC_GET_TWEET_BY_ID_URL',
  TWITTER_GUEST_TOKEN_API_URL: 'TWITTER_GUEST_TOKEN_API_URL',
  TWIITER_GET_TWEET_BY_ID_URL: 'TWIITER_GET_TWEET_BY_ID_URL',
  TWITTER_REPLY_TWEET_URL: 'TWITTER_REPLY_TWEET_URL',
  // encrypt
  ENCRYPTION_IV: 'ENCRYPTION_IV',
  ENCRYPTION_KEY: 'ENCRYPTION_KEY',

  // solana
  SOLANA_CLUSTER: 'SOLANA_CLUSTER',

  // frontend
  FRONTEND_URL: 'FRONTEND_URL',

  // redis
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASSWORD: 'REDIS_PASSWORD',
  REDIS_DB: 'REDIS_DB',

  // queue
  BULL_BOARD_PASSWORD: 'BULL_BOARD_PASSWORD',
  QUEUE_REDIS_DB: 'QUEUE_REDIS_DB',
  // llm queue
  GOOGLE_GEMINI_LLM_SERVICE_QUEUE_JOB_ATTEMPTS:
    'GOOGLE_GEMINI_LLM_SERVICE_QUEUE_JOB_ATTEMPTS',
  GOOGLE_GEMINI_LLM_SERVICE_QUEUE_JOB_BACKOFF_DELAY:
    'GOOGLE_GEMINI_LLM_SERVICE_QUEUE_JOB_BACKOFF_DELAY',
  GOOGLE_GEMINI_LLM_SERVICE_QUEUE_RATE_MAX:
    'GOOGLE_GEMINI_LLM_SERVICE_QUEUE_RATE_MAX',
  GOOGLE_GEMINI_LLM_SERVICE_QUEUE_RATE_DURATION:
    'GOOGLE_GEMINI_LLM_SERVICE_QUEUE_RATE_DURATION',

  // llm provider
  FREE_GOOGLE_GEMINI_LLM_SERVICE_API_KEYS:
    'FREE_GOOGLE_GEMINI_LLM_SERVICE_API_KEYS',
  PAID_GOOGLE_GEMINI_LLM_SERVICE_API_KEYS:
    'PAID_GOOGLE_GEMINI_LLM_SERVICE_API_KEYS',
};

export const RedisKeys = {
  TWITTER_GUEST_TOKEN: 'twitter_guest_token',
};

export const GoogleLlmQueueService = {
  QUEUE_NAME: 'google-gemini-llm-service',
  JOBS: {
    EXAMPLE: 'example',
  },
};

export const ExampleQueueService = {
  QUEUE_NAME: {
    EXAMPLE_QUEUE: 'example-queue',
  },
  JOBS: {
    EXAMPLE_JOB: 'example-job',
  },
};
